### PR TITLE
Add funding and recognition to lifecycle phases

### PR DESCRIPTION
**Pull request by maherou**
I think we need to keep in mind funding issues.  Also, while credit is discussed elsewhere, I think it should be part of the mission statement as well.  Please use, modify or ignore these edits as you see fit.

### CODE REVIEW

**Comment by danielskatz** [comment]
Thanks @maherou 

I'm supportive of adding the funding part, though I wonder if it can be generalized a bit to support, or if that sounds too much like user support.  

I'm less sure that adding recognition here make sense, though I agree that it is important.

Other opinions are welcome.

**Comment by maherou** [comment]
Sure, I understand your concerns.  I would like recognition to be somehow very prominent.  The more time I spend working with people in CSE software, the more I see that lack of professional recognition is a fundamental impediment to progress in improving software investments in many ways.

Perhaps the mission should be more broadly stated, so that lifecycle is not the primary focus.

**Comment by ljhwang** [comment]
I am apprehensive on adding explicitly "funding" as I think it tends to change the character of an organization.  "Challenges" can imply many things that are further defined in the Vision and Focus Areas.

**Comment by danielskatz** [comment]
I wonder if we should pull the definition of the life-cycle into a a separate sentence?

I also am now thinking that acquiring the resources or forming the team/community around a software project is indeed a significant part of the life-cycle, but is more than just funding.

**Comment by gridrebel** [comment]
I agree with Dan on preferring something around "addressing resources and team aspects of software projects" rather than explicitly adding funding if this is for the mission or vision. I would also pull out the life-cycle definition as well -- would even remove it rather than make it a separate sentence, think it is too detailed for either a vision or mission. The focus areas should be the place for details or highlighting specific questions.

**Comment by ljhwang** [comment]
I agree. Should we just keep the mission simple and change the statement to "addressing the challenges related to research software" and move the details down to the Vision or Focus Area where we also define "sustainable software"?
Could be something like: WSSSPE promotes sustainable research software by addressing the twin challenges of resource availability and support throughout software life-cycle by: 
And the add the definition of sustainable and life-cycle after the bullet points?

**Comment by kyleniemeyer** [comment]
I agree that both of these issues are important, although I think funding might be implicit if the recognition of software's importance (and therefore the recognition of software contributions) is established.

**Comment by danielskatz** [comment]
I don't think funding is implicit, except in terms of assembling the resources needed for a given project as part of its life-cycle.

**Comment by danielskatz** [comment]
Ok, @maherou , thanks for bringing up this discussion - I'm going to merge your pull request, then make some more changes based on the discussion in this thread.

**Comment by kyleniemeyer** [comment]
@danielskatz Right, it isn't necessarily implicit in the current mission—I meant more that funding may not need to be explicitly mentioned if recognition is there.

(I also just realized I missed all the new comments after @maherou's second... so my contribution was not particularly relevant to where the discussion actually was.)

**Comment by danielskatz** [comment]
Everyone, please see what you think of the new version, and if you have concerns, please open a new issue for further discussion.

**Comment by ljhwang** [comment]
The grammar police note that the bullet points are not parallel in structure. To begin with a noun:
- resources for individuals, teams and communities 

(oxford comma notwithstanding)

**Comment by danielskatz** [comment]
Let's stop discussing in this closed PR and start in a new issue...

**Pull request merged**
